# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11KeSeV9cY_xLQl51bj4TIXwvVE_j_UnX
"""

from selenium import webdriver
driver = webdriver.Chrome()
driver.get("http://news.naver.com/main/home.nhn")
titleEles = driver.find_elements_by_css_selector(".newsnow_tx_inner")
for title in titleEles :
  print(title.text)

